### ISSUE TITLE
Join all channels on connect

### ISSUE THREAD

**Issue by mweinelt** [f-breidenstein/CptHook#1]
After connecting to the server all channels should be joined. A missing bot in a channel is an indicator that something is wrong, so that is helpful.

**Comment by f-breidenstein** [comment]
Update: 
I started a new branch called 'makeover' a few days ago which also changes the structure of a CptHook module. This also includes a getAllChannel() functions which we can call durint initialization to easily gather a list of all channels from all modules and join them.

**Comment by f-breidenstein** [comment]
The new branch just got merged into development.
